name: MythicErrorFixer
version: 1.0.0
main: net.azisaba.mythicerrorfixer.MythicErrorFixer
api-version: '1.15'
depend: [MythicMobs]
description: Fixes MythicMobs errors automatically.
authors: [Azisaba Network]

commands:
  mythicfixer:
    description: MythicErrorFixer main command
    aliases: [mfixer]
    permission: mythicerrorfixer.admin

permissions:
  mythicerrorfixer.admin:
    description: Allows to use /mythicfixer
    default: op
